feat: update configure script to 1.2.1

diff --git a/.bmeme/build/bin/c b/.bmeme/build/bin/c
--- a/.bmeme/build/bin/c
+++ b/.bmeme/build/bin/c
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 
+set -e
+SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
+source "${SCRIPT_DIR}/../common/lib.sh"
+
 PWD=$(pwd)
 while [[ "$PWD" != "" && ! -e "$PWD/.bmeme" ]]; do
   PWD=${PWD%/*}
@@ -8,7 +12,7 @@ done
 FOUND=$PWD
 
 if [[ "${FOUND}" = "" ]]; then
-  echo "Unable to find parent bmeme project!"
+  echo -e "${CR}Error${CN} - Unable to find parent bmeme project!"
   exit -1
 fi
 
@@ -23,5 +27,5 @@ done
 CMD="${QUOTEDCMD[*]}"
 
 pushd ${FOUND} > /dev/null
-.bmeme/bin/app cd ".${REL_DIR}" \; ${CMD}
+${APP_BIN} cd ".${REL_DIR}" \; ${CMD}
 popd > /dev/null
